version: '2'

services:
  payment:
    build:
      context: .
      dockerfile: docker/queue-master/Dockerfile
    image: TAG_TO_REPLACE
    hostname: queue-master
    restart: always
    environment:
      - DT_CUSTOM_PROP=app=queue-master,environment=dev
    cap_drop:
    - all
    cap_add:
    - NET_BIND_SERVICE
    read_only: true
    ports:
    - "8084:80"
